apiVersion: v1
kind: Service
metadata:
  name: { include "microservices-demo-openapi.fullname" . }
spec:
  type: { .Values.service.type }
  ports:
    - port: { .Values.service.port }
      targetPort: 3000
  selector:
    app: { include "microservices-demo-openapi.fullname" . }
