apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservices-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservices-demo
  template:
    metadata:
      labels:
        app: microservices-demo
    spec:
      containers:
      - name: app
        image: yourrepo/microservices-demo:latest
        ports:
        - containerPort: 3000
